language: java

jdk:
  - oraclejdk8

branches:
  only:
  - master

stages:
  - name: build
    if: type = pull_request
  - name: deploy
    if: branch != master AND type != pull_request

services:
  - mysql

jobs:
  include:
    - stage: build
      cache:
        directories:
        - $HOME/.m2
      before_install:
        - mysql -e 'CREATE DATABASE testing;'
      script:
        - mvn clean install
        
    - stage: deploy
      before_install:
        - echo -e "RUNNING"
      script:
        - mvn springboot run

notifications:
  email:
    - israj.haliri@gmail.com
